(function(){
const K={users:'examyAdminUsers',payments:'examyAdminPayments'};
function get(k,d=[]){try{return JSON.parse(localStorage.getItem(k))||d}catch(e){return d}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function seed(){let u=get(K.users); if(!u.length){u=[{id:'USR001',name:'Demo Student',email:'student@examyweb.in',exam:'JEE Main',plan:'Starter',status:'pending',expires:''}];save(K.users,u)} if(!get(K.payments).length)save(K.payments,[{id:'PAY001',userId:'USR001',email:'student@examyweb.in',amount:99,utr:'DEMO123456',status:'PENDING',date:new Date().toLocaleDateString('en-IN')}])}
function render(){const users=get(K.users), pays=get(K.payments);document.getElementById('totalUsers').textContent=users.length;document.getElementById('pendingCount').textContent=pays.filter(x=>x.status==='PENDING').length;document.getElementById('activeCount').textContent=users.filter(x=>x.status==='active').length;document.getElementById('revenue').textContent='₹'+users.filter(x=>x.status==='active').reduce((a,x)=>a+(x.amount||({Starter:99,Pro:199,Elite:299}[x.plan]||0)),0);document.getElementById('usersTable').innerHTML='<div class="row head"><span>USER</span><span>EXAM</span><span>PLAN</span><span>STATUS</span><span>ACTION</span></div>'+users.map(u=>`<div class="row"><span><b>${u.name}</b><br><small>${u.email}</small></span><span>${u.exam||'-'}</span><span>${u.plan||'-'}</span><span><i class="status ${u.status==='active'?'active':''}">${u.status==='active'?'ACTIVE':'PENDING'}</i></span><span class="actions"><button class="grant" data-grant="${u.id}">Grant 30d</button><button data-revoke="${u.id}">Revoke</button></span></div>`).join('');document.getElementById('paymentsTable').innerHTML='<div class="row head"><span>USER</span><span>AMOUNT</span><span>UTR</span><span>STATUS</span><span>ACTION</span></div>'+pays.map(p=>`<div class="row"><span>${p.email}</span><span>₹${p.amount}</span><span>${p.utr}</span><span><i class="status ${p.status==='PAID'?'active':'pending'}">${p.status}</i></span><span class="actions"><button class="grant" data-pay="${p.id}">Approve</button></span></div>`).join('');
const themes=window.EXAMY_THEMES||{};const active=localStorage.getItem('examyTheme')||'classic';document.getElementById('activeTheme').textContent=themes[active]?.name||active;document.getElementById('themeGrid').innerHTML=Object.entries(themes).map(([id,t])=>`<div class="theme-card ${id===active?'active':''}" data-theme-id="${id}"><div class="swatch" style="background:linear-gradient(135deg,${t.bg},${t.primary} 65%,${t.primary2})"></div><b>${t.name}</b><small>${id===active?'ACTIVE •':'Click to activate'}</small></div>`).join('');
}
function grant(id){let u=get(K.users);u=u.map(x=>x.id===id?({...x,status:'active',expires:new Date(Date.now()+30*864e5).toISOString().slice(0,10),amount:x.amount||({Starter:99,Pro:199,Elite:299}[x.plan]||99)}):x);save(K.users,u);let p=get(K.payments);p=p.map(x=>x.userId===id?({...x,status:'PAID'}):x);save(K.payments,p);render()}
function revoke(id){save(K.users,get(K.users).map(x=>x.id===id?({...x,status:'pending'}):x));render()}
document.addEventListener('click',e=>{const g=e.target.closest('[data-grant]');if(g)grant(g.dataset.grant);const r=e.target.closest('[data-revoke]');if(r)revoke(r.dataset.revoke);const a=e.target.closest('[data-pay]');if(a){const p=get(K.payments).find(x=>x.id===a.dataset.pay);if(p){let u=get(K.users);u=u.map(x=>x.id===p.userId?({...x,status:'active',expires:new Date(Date.now()+30*864e5).toISOString().slice(0,10),amount:p.amount}):x);save(K.users,u);save(K.payments,get(K.payments).map(x=>x.id===p.id?({...x,status:'PAID'}):x));render()}}const t=e.target.closest('[data-theme-id]');if(t){localStorage.setItem('examyTheme',t.dataset.themeId);location.reload()}});document.getElementById('seed').onclick=()=>{localStorage.removeItem(K.users);localStorage.removeItem(K.payments);seed();render()};seed();render();
})();
