const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const KEY="jeeStudyOS_v1";
let data=JSON.parse(localStorage.getItem(KEY)||'{"sessions":[],"todos":[],"backlogs":[],"questions":{"pyq":0,"module":0,"adv":0},"mocks":[],"revisions":[],"chapters":{},"streak":0}');
const save=()=>{localStorage.setItem(KEY,JSON.stringify(data));renderAll()};
const today=new Date().toISOString().slice(0,10);
$("#sessionDate").value=today; $("#revisionDate").value=today;
$("#todayText").textContent=new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"short"});
function go(page){$$(".page").forEach(x=>x.classList.remove("active"));$("#"+page)?.classList.add("active");$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("#pageTitle").textContent=page==="todo"?"Daily Planner":page[0].toUpperCase()+page.slice(1);$("#sidebar").classList.remove("open");window.scrollTo(0,0)}
$$("[data-page]").forEach(b=>b.addEventListener("click",()=>go(b.dataset.page)));
$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");

$("#sessionForm").onsubmit=e=>{e.preventDefault();data.sessions.unshift({date:$("#sessionDate").value,subject:$("#sessionSubject").value,hours:+$("#sessionHours").value,topic:$("#sessionTopic").value});e.target.reset();$("#sessionDate").value=today;save()};
$("#todoForm").onsubmit=e=>{e.preventDefault();data.todos.push({text:$("#todoInput").value,subject:$("#todoSubject").value,done:false});e.target.reset();save()};
$("#backlogForm").onsubmit=e=>{e.preventDefault();data.backlogs.push({text:$("#backlogInput").value,priority:$("#backlogPriority").value,done:false});e.target.reset();save()};
$("#questionForm").onsubmit=e=>{e.preventDefault();data.questions[$("#qType").value]+= +$("#qNumber").value;e.target.reset();save()};
$("#mockForm").onsubmit=e=>{e.preventDefault();data.mocks.unshift({name:$("#mockName").value,score:+$("#mockScore").value,max:+$("#mockMax").value,percentile:$("#mockPercentile").value});e.target.reset();$("#mockMax").value=300;save()};
$("#revisionForm").onsubmit=e=>{e.preventDefault();data.revisions.push({text:$("#revisionTopic").value,date:$("#revisionDate").value,done:false});e.target.reset();$("#revisionDate").value=today;save()};

function toggle(arr,i){arr[i].done=!arr[i].done;save()}
function del(arr,i){arr.splice(i,1);save()}
function renderTodos(){let el=$("#todoList");el.innerHTML=data.todos.length?data.todos.map((t,i)=>`<div class="todo-row ${t.done?"done":""}"><div class="row-left"><input type="checkbox" ${t.done?"checked":""} onchange="toggle(data.todos,${i})"><span>${esc(t.text)}</span><span class="tag">${t.subject}</span></div><button class="ghost" onclick="del(data.todos,${i})">×</button></div>`).join(""):`<p class="muted">No tasks yet. Add your first task above.</p>`}
function renderBacklog(){let el=$("#backlogList");el.innerHTML=data.backlogs.length?data.backlogs.map((t,i)=>`<div class="todo-row ${t.done?"done":""}"><div class="row-left"><input type="checkbox" ${t.done?"checked":""} onchange="toggle(data.backlogs,${i})"><span>${esc(t.text)}</span><span class="tag ${t.priority.toLowerCase()}">${t.priority}</span></div><button class="ghost" onclick="del(data.backlogs,${i})">×</button></div>`).join(""):`<p class="muted">Backlog empty 🎉</p>`}
function renderSessions(){let el=$("#sessionList");el.innerHTML=data.sessions.length?data.sessions.slice(0,20).map(s=>`<div class="list-row"><span><b>${esc(s.topic)}</b><small class="muted"> · ${s.subject} · ${s.date}</small></span><b>${s.hours}h</b></div>`).join(""):`<p class="muted">No study logged yet.</p>`}
function renderQuestions(){["pyq","module","adv"].forEach(k=>$("#"+k).textContent=data.questions[k]);$("#questionCount").textContent=data.questions.pyq+data.questions.module+data.questions.adv}
function renderRevisions(){let el=$("#revisionList");el.innerHTML=data.revisions.length?data.revisions.map((r,i)=>`<div class="todo-row ${r.done?"done":""}"><div class="row-left"><input type="checkbox" ${r.done?"checked":""} onchange="toggle(data.revisions,${i})"><span>${esc(r.text)}</span><span class="tag">${r.date}</span></div><button class="ghost" onclick="del(data.revisions,${i})">×</button></div>`).join(""):`<p class="muted">No revisions scheduled.</p>`}
function renderMocks(){let el=$("#mockList");el.innerHTML=data.mocks.length?data.mocks.map(m=>`<div class="list-row"><span><b>${esc(m.name)}</b><small class="muted"> · ${m.score}/${m.max}</small></span><b>${m.percentile?m.percentile+"%ile":Math.round(m.score/m.max*100)+"%"}</b></div>`).join(""):`<p class="muted">No mock tests logged.</p>`}
function subjectHours(){return ["Physics","Chemistry","Maths"].map(s=>[s,data.sessions.filter(x=>x.subject===s).reduce((a,b)=>a+b.hours,0)])}
function renderSubjects(target="#subjectBars"){let el=$(target), vals=subjectHours(), max=Math.max(1,...vals.map(x=>x[1]));el.innerHTML=vals.map(([s,h])=>`<div class="subject"><div class="subject-top"><span>${s}</span><b>${h.toFixed(1)}h</b></div><div class="track"><div class="fill" style="width:${h/max*100}%"></div></div></div>`).join("")}
function renderChart(){let days=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let key=d.toISOString().slice(0,10),h=data.sessions.filter(s=>s.date===key).reduce((a,b)=>a+b.hours,0);days.push([d.toLocaleDateString("en-IN",{weekday:"short"}),h])}let max=Math.max(1,...days.map(x=>x[1]));$("#weekChart").innerHTML=days.map(([d,h])=>`<div class="barwrap"><b>${h? h.toFixed(1):""}</b><div class="bar" style="height:${Math.max(4,h/max*125)}px"></div><small>${d}</small></div>`).join("")}
function renderDashboard(){let todayH=data.sessions.filter(s=>s.date===today).reduce((a,b)=>a+b.hours,0),pct=Math.min(100,todayH/7*100);$("#todayHours").textContent=todayH.toFixed(1);$("#goalText").textContent=`${todayH.toFixed(1)}h / 7h`;$("#goalRing").textContent=Math.round(pct)+"%";$("#goalRing").style.background=`conic-gradient(#9b8be3 ${pct}%, #d9c7f5 0)`;$("#streak").textContent=data.streak||0;$("#backlogOpen").textContent=data.backlogs.filter(x=>!x.done).length+" open";$("#revisionDue").textContent=data.revisions.filter(x=>!x.done&&x.date<=today).length+" due";renderChart();renderSubjects()}
function renderAnalytics(){let total=data.sessions.reduce((a,b)=>a+b.hours,0), days=new Set(data.sessions.map(s=>s.date)).size, done=data.todos.filter(x=>x.done).length;$("#totalHours").textContent=total.toFixed(1);$("#avgHours").textContent=(days?total/days:0).toFixed(1);$("#completion").textContent=(data.todos.length?Math.round(done/data.todos.length*100):0)+"%";renderSubjects("#analyticsSubjects")}
const chapters={Physics:["Units & Dimensions","Kinematics","NLM","Work Power Energy","Rotation","COM & Collision","Gravitation","Electrostatics","Current Electricity","Magnetism","EMI & AC","Optics"],Chemistry:["Mole Concept","Atomic Structure","Chemical Bonding","Thermodynamics","Equilibrium","Electrochemistry","Solutions","GOC","Hydrocarbons","Amines","Biomolecules"],Maths:["Quadratic","Sequence & Series","Trigonometry","Straight Lines","Circle","Limits","Differentiation","AOD","Integration","Matrices & Determinants","Vector 3D"]};
function renderSyllabus(){let el=$("#syllabusCards");el.innerHTML=Object.entries(chapters).map(([s,cs])=>`<div class="card"><h2 class="syllabus-subject">${s}</h2>${cs.map((c,i)=>{let k=s+i,d=!!data.chapters[k];return `<div class="chapter ${d?"done":""}"><span>${c}</span><button onclick="data.chapters['${k}']=!data.chapters['${k}'];save()">${d?"✓":"○"}</button></div>`}).join("")}</div>`).join("")}
function esc(x){return String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function renderAll(){renderTodos();renderBacklog();renderSessions();renderQuestions();renderRevisions();renderMocks();renderDashboard();renderAnalytics();renderSyllabus()}
let timer=null, seconds=1500;
function timerDraw(){let m=String(Math.floor(seconds/60)).padStart(2,"0"),s=String(seconds%60).padStart(2,"0");$("#timerDisplay").textContent=`${m}:${s}`}
$("#timerStart").onclick=()=>{if(timer){clearInterval(timer);timer=null;$("#timerStart").textContent="Start"}else{timer=setInterval(()=>{seconds--;timerDraw();if(seconds<=0){clearInterval(timer);timer=null;alert("Focus session complete! Log it in Study Tracker.");$("#timerStart").textContent="Start"}},1000);$("#timerStart").textContent="Pause"}};
$("#timerReset").onclick=()=>{clearInterval(timer);timer=null;seconds=1500;timerDraw();$("#timerStart").textContent="Start"};
$$(".presets button").forEach(b=>b.onclick=()=>{clearInterval(timer);timer=null;seconds=+b.dataset.min*60;timerDraw();$("#timerStart").textContent="Start"});
renderAll();timerDraw();
